config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy]
  resources :reviews, except: [:destroy]

  root 'homes#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/users/:id/destroy', to: 'users#destroy', as: 'delete_user'
  get '/reviews/:id/destroy', to: 'reviews#destroy', as: 'delete_review'
  get '/meetups/:id/join', to: 'attendees_meetups#new', as: 'add_to_meetup'
  post '/meetups/:id/join', to: 'attendees_meetups#create', as: 'attendees_meetups'
  get '/meetups/:id/cancel', to: 'attendees_meetups#destroy', as: 'cancel_attendance'
  resources :resorts, only: [:index, :show]
  resources :conversation, only: [:create, :destroy, :show]
  resources :messages
  resources :meetups


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/meetup.rb
class Meetup < ActiveRecord::Base 
    belongs_to :resort
    has_many :attendees_meetups
    belongs_to :organiser, :class_name => "User", :foreign_key => :organiser_id
    has_many :attendees, :class_name => "User", through: :attendees_meetups

     def self.search(search)
        if search 
            resort = Resort.find_by(resort_name: search)
            if resort
                self.where(resort_id: resort)
            else
                Meetup.all
            end
        else
            Meetup.all
        
        end
    end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
    def index
        @meetups = Meetup.search(params[:search])
    end

    def new 
        @meetup = Meetup.new
    end

    def show 
    
        @meetup = Meetup.find(params[:id])
        #retrieve all users with a meetup id from params[:id]
        @attending_ids = AttendeesMeetup.where(meetup_id: params[:id]).map(&:attendee_id).uniq
    end

    def create 
        @meetup = Meetup.new(meetup_params)
        if @meetup.save
            redirect_to meetup_path(@meetup.id)
        else 
            render :new
        end
    end

    def edit 
        @meetup = Meetup.find(params[:id])
    end

    def update
        @meetup = Meetup.find(params[:id])
        if @meetup.update(meetup_params)
            redirect_to meetup_path(@meetup.id)
        else 
            render :edit
        end
    end

    def destroy 
        @meetup = Meetup.find(params[:id])
        @meetup.destroy
        redirect_to meetups_path
    end

    private 
    def meetup_params
        params.require(:meetup).permit!
    end
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/meetups/_form.html.erb
<div align='center'>
<p>
<%= form_for(@meetup) do |f| %>
<p>
<%= f.label :event_name %><br>
<%= f.text_field :event_name %><br><br>
</p>

<p>
<%= f.label :description %><br>
<%= f.text_area :description %><br><br>
</p>

<p>
<%= f.label :rendezvous %><br>
<%= f.text_field :location %><br><br>
</p>

<p>
<%= f.label :when%><br>
<%= f.datetime_select :date_time, :order => [:month, :day] %><br><br>
</p>

<p>
<%= f.label :resort_id %><br>
<%= f.collection_select(:resort_id, Resort.all, :id, :resort_name) %><br><br>
</p>
 
<%= f.hidden_field :organiser_id, :value => current_user.id %><br>


<p><%= f.submit %><p>

<% end %>
</p>
</div>

app/views/meetups/edit.html.erb
<h3 align='center'>Edit Meetup </h3>

<%=render 'form'  %>

app/views/meetups/index.html.erb
<h1 align='center'>All Meetups</h1>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<h3> Search by Resort:</h3>
  <%= form_tag(meetups_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag ("Search by Resort") %>
<% end %>

<table>
    <thead>
    <tr>
        <th>Event</th>
        <th>Resort</th>
        <th>Date & Time</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <tr>
        <% @meetups.each do |meetup| %>
        <td><%= link_to meetup.event_name, meetup_path(meetup) %></td>
        <td><%= link_to meetup.resort.resort_name, resort_path(meetup.resort_id) %></td>
        <td><%= meetup.date_time %></td>
    </tr>
    <% end %>
</tbody>
</table>

app/views/meetups/new.html.erb
<h3 align= 'center'>Create A New Meetup</h3>
<% if @meetup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meetup.errors.count, "error") %> prohibited this meetup from being created:</h2>

      <ul>
        <% @meetup.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%=render 'form'  %>

app/views/meetups/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<h4><%= @meetup.event_name %></h4><br>
<p>
<strong>Hosted by:</strong> <%= @meetup.organiser.full_name %></p>
<p>
<strong>Event Description:</strong> <%= @meetup.description %></p>
<p>
<strong>Location: </strong> <%= @meetup.resort.resort_name %>, <%= @meetup.location %></p>
<p>
<strong>Date & Time: </strong><%= @meetup.date_time %></p>
<p>
<strong> Attending: <% @attending_ids.each do |id| %>
                        <ul>
                            <li> <%= link_to User.find(id).full_name, user_path(id)  %></li>
                        </ul>
                    <% end %>
<br>

<% if @attending_ids.include?(session[:user_id])  %>
    <%= link_to "Cancel attendance", cancel_attendance_path %>
<% end %>
<%= link_to "Join Meetup!", add_to_meetup_path %>

<%= link_to "All Meetups", meetups_path %>