config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy]
  resources :reviews, except: [:destroy]

  root 'homes#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/users/:id/destroy', to: 'users#destroy', as: 'delete_user'
  get '/reviews/:id/destroy', to: 'reviews#destroy', as: 'delete_review'
  get '/meetups/:id/join', to: 'attendees_meetups#new', as: 'add_to_meetup'
  post '/meetups/:id/join', to: 'attendees_meetups#create', as: 'attendees_meetups'
  get '/meetups/:id/cancel', to: 'attendees_meetups#destroy', as: 'cancel_attendance'
  resources :resorts, only: [:index, :show]
  resources :conversation, only: [:create, :destroy, :show]
  resources :messages
  resources :meetups


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :resorts, through: :reviews
    has_many :meetups, through: :attendees_meetups
    has_many :attendees_meetups

    validates :first_name, presence: true
    validates :last_name, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true,
                uniqueness: {case_sensitive: true},
                length: {minimum: 5, maximum: 105 },
                format: {with: VALID_EMAIL_REGEX}
    validates :password, presence: true
    validates :age, presence: true

    has_secure_password

    def full_name
        if self 
            first_name + " " + last_name
        else 
            "Chris K"
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_user, except: [:index, :show, :new, :create]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :require_login, only: [:edit, :update, :destroy]
  before_action :current_user, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    meetups = AttendeesMeetup.where(attendee_id: session[:user_id]).map(&:meetup_id).uniq
    @my_meetups = Meetup.where(id: meetups).map(&:event_name)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        session[:user_id] = @user.id
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.destroy(session[:user_id])
    session.destroy
    redirect_to '/'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :age)
    end

    def require_login 
      return head(:forbidden) unless session.include? :user_id
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" align='center'>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %><br>
  </div>

  <div class="field" align='center'>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %><br>
  </div>

  <div class="field" align='center'>
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
  </div>

  <div class="field" align='center'>
    <%= form.label :password %><br>
    <%= form.password_field :password %><br>
  </div>

  <div class="field" align='center'>
    <%= form.label :age %><br>
    <%= form.number_field :age %><br>
  </div>

  <div class="actions" align='center'><br>
    <%= form.submit %><br>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 align='center'>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path(@user) %> |
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Reviews</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.age %></td>
        <td><%= link_to "Reviews", review_path(user) %>
        <td><%= link_to 'Profile', user %></td>
  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% if flash[:success] %>
  <p><%= flash[:success] %></p>
<% end %>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p> My Meetups </p>
<% @my_meetups.each do |event| %>
<ul>
  <li><%= event %></li>
</ul>
<% end %>


<% if session[:user_id] == @user.id %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'New Meetup', new_meetup_path %> |
  <%= link_to 'New Review', new_review_path %> |
  <%= link_to 'Delete Account', delete_user_path%>
<% end %>