config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy]
  resources :reviews, except: [:destroy]

  root 'homes#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/users/:id/destroy', to: 'users#destroy', as: 'delete_user'
  get '/reviews/:id/destroy', to: 'reviews#destroy', as: 'delete_review'
  get '/meetups/:id/join', to: 'attendees_meetups#new', as: 'add_to_meetup'
  post '/meetups/:id/join', to: 'attendees_meetups#create', as: 'attendees_meetups'
  get '/meetups/:id/cancel', to: 'attendees_meetups#destroy', as: 'cancel_attendance'
  resources :resorts, only: [:index, :show]
  resources :conversation, only: [:create, :destroy, :show]
  resources :messages
  resources :meetups


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :current_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:update]

    def show 
        @review = Review.find(params[:id])
    end

    def index 
        @reviews = Review.all
    end

    def new 
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        if @review.valid?
            @review.save
            redirect_to review_path(@review)
        else
            render :new
        end
    end

    def edit
        @review = Review.find(params[:id])
    end

    def update 
        @review = Review.find(params[:id])
        if @review.update(review_params)
            redirect_to review_path(@review)
        else
            render :edit
        end
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        flash[:notice] = "You have deleted your review."
        redirect_to reviews_path
    end

    private
    def review_params
        params.require(:review).permit!
    end


    def require_same_user 
        if current_user != @review.user.id
            flash[:danger] = "You can only edit or delete your own review."
            redirect_to user_path(current_user)
        end
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<% if @review.errors.any? %>
    <div id="error_explanation"> 
        <h2>
            <%= pluralize(@review.errors.count, "error") %>
            prohibited this review from being saved!
        </h2>

        <ul>
        <% @review.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>



<%= form_for(@review) do |f| %>

    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>

    <%= f.label :content %><br>
    <%= f.text_area :content %><br><br>

    <%= f.label :rating %><br>
    <%= f.number_field :rating %><br><br>

    <%= f.label :resort_id %><br>
    <%= f.collection_select :resort_id, Resort.all, :id, :resort_name %><br><br>

    <%= f.hidden_field :user_id, :value => session[:user_id] %><br>

 
    <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1> Edit Review </h1>

<%= render "form" %>

app/views/reviews/index.html.erb
<h1> Welcome to the Reviews index page! </h1>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class='grid-container'>
<% @reviews.each do |review| %>
    <ul>
        <li> <%= link_to review.title, review_path(review) %></li>
        
    </ul>
<% end %>
</div>

app/views/reviews/new.html.erb
<%# <div class="jumbotron">
  <div class="col-md-12">
  </div>
  <div class="col-md-12">
    <div style='width: 100%;'>
      <div id="map" style='width: 100%; height: 400px;'></div>
    </div>
  </div>
</div>
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": 31.5204,
        "lng": 74.3587,
        "picture": {
          "url": "http://icon-park.com/imagefiles/location_map_pin_yellow5.png",
          "width":  32,
          "height": 32
        },
        "infowindow": "hello!"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script> %>

<h1> New Review Form </h1>

<%= render "form" %>

app/views/reviews/show.html.erb
<h2><%= @review.title %><br></h2>
<h3>Authored by: <%= @review.user.first_name %></h3><br>
<%= @review.content %><br>
<% @review.rating.to_i.times do %>
<span class='glyphicon glyphicon-star' ></span>
<% end %>


<% if session[:user_id] == @review.user.id %>
    <%= link_to 'Edit Review', edit_review_path(@review) %> 
    <%= link_to 'Delete Review', delete_review_path%>
<% end %>

<%= link_to "All Reviews", reviews_path %>