config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy]
  resources :reviews, except: [:destroy]

  root 'homes#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/users/:id/destroy', to: 'users#destroy', as: 'delete_user'
  get '/reviews/:id/destroy', to: 'reviews#destroy', as: 'delete_review'
  get '/meetups/:id/join', to: 'attendees_meetups#new', as: 'add_to_meetup'
  post '/meetups/:id/join', to: 'attendees_meetups#create', as: 'attendees_meetups'
  get '/meetups/:id/cancel', to: 'attendees_meetups#destroy', as: 'cancel_attendance'
  resources :resorts, only: [:index, :show]
  resources :conversation, only: [:create, :destroy, :show]
  resources :messages
  resources :meetups


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/resort.rb
class Resort < ActiveRecord::Base
    has_many :reviews 
    has_many :meetups 
    has_many :users, through: :reviews
    
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
    def index 
        @resorts = Resort.all
        # @region_name = APIRequestMaker.new.re
    end

    def show 
        @resort = Resort.find(params[:id])
    end

    def new
        @resort = Resort.new
    end

    def edit
        @resort = Resort.find(params[:id])
    end

    def create
        @resort = Resort.new(resort_params)
        if @resort.valid?
            @resort.save
            redirect_to resort_path(@resort)
        else
            render :new
        end
    end

    def update
        @resort = Resort.find(params[:id])
        if @resort.update(resort_params)
            redirect_to resort_path(@resort)
        else
            render :edit
        end
    end

    private

    def resort_params
        params.require(:resort).permit!
    end

end

app/helpers/resorts_helper.rb
module ResortsHelper
end

app/views/resorts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Resorts</h1>

<table>
    <thead>
    <tr>
    <th>Resorts</th>
    </tr>
    </thead>

    <tbody>
    <% @resorts.each do |resort| %>
    <tr>
    <td><%= link_to resort.resort_name, resort_path(resort.id) %>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/resorts/show.html.erb
<h4 align= 'center'><%= @resort.resort_name %></h4><br>
<div align= 'center'>
<p>
<% if @resort.location %>
<strong>Location:</strong> <%= @resort.location %></p>
<p>
<% end %>
<p>
<strong>Population: </strong><%= @resort.population%></p>
<p>
</div>
<img src= <%= @resort.piste_map %> align= 'center' width = 90%></p>
<p>
<strong>Meetups happening here:</strong>
<% @resort.meetups.each do |meetup| %>
<ul>
<li><%= link_to meetup.event_name, meetup_path(meetup.id) %></li>
</ul>
<% end %>
<br>

<strong>Reviews:</strong>
<% @resort.reviews.each do |review| %>
<ul>
<li><%= link_to review.title, review_path(review.id) %> - <%= link_to review.user.full_name, user_path(review.user) %>, <%= review.rating %></li>
</ul>
<% end %>


<iframe
  align="left"
  width="400"
  height="350"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDp3KAT8TqZXXI9jr3Fims0GmBTbRg1LwE
    &q=<%=@resort.resort_name%>+<%=@resort.resort_name%>" allowfullscreen>
</iframe>